### ISSUE TITLE
Question. How do you switch off the debug messages

### ISSUE THREAD

**Issue by JacoFourie** [chainq/mosquitto-p#1]
Hi. Thanks for this binding. It works well. I have one question. I get a lot of debug messages coming back from the library. What is the correct way to switch it off?

Regards.

**Comment by chainq** [comment]
The easiest way to mute debug output is to override the logger function with function `mqtt_setlogfunc`. The function prototype is type `mqtt_logfunc`, you can simply override it with an empty function. If you just want to limit messages from the underlying `libmosquitto` library promoted through `mqttclass`, you need to override the `OnLog` property with your own logging function, where you can filter various log levels appearing from the library (like the very verbose DEBUG messages). Does this help?

**Comment by chainq** [comment]
Actually, I could add a property to the `mqttclass` which would allow setting the log level in the built-in `OnLog`, and improve that function to support filtering. A pull request is always welcomed. :) But I'll add it too, I just can't promise it will be done short-term.

**Comment by JacoFourie** [comment]
Yes that would be great. I have never done a pull request. What do you want me to do ?

**Comment by chainq** [comment]
Actually... Scrap that. I now looked into the code again, and I realized it needs a bit more changes, to make this properly configurable, on both the `libmosquitto` level and the `mqttclass` level. I will try to find some time, because on the `mqttclass` level are still some hardwired messages, which can be only silenced using the first method (completely overwriting the `logfunc` and muting the output that way).

**Comment by chainq** [comment]
See commit 351a9ff0. Should fix your problem. In `TMQTTClass` constructor, there's now an additional argument, which lets you set the logging level. Use `MOSQ_LOG_NODEBUG` to disable only DEBUG logs, and keep everything else. Afterwards via `MQTTLogLevel` property it lets you configure which log messages you want to see. It also lets you finetune of what `libmosquitto` messages are let through, via `MOSQLogLevel` property. By default both of these properties will use the value passed to the constructor. Also added a few other bits here and there to silence various other bits, but if you only use `TMQTTClass` these aren't important for you. Please test.

**Comment by JacoFourie** [comment]
This works great thanks a lot for your effort. One last question. I see there are some Writestr() still.

What do they do ? I still get some messages even if I set the logger to no log.

writestr(tmp,'State change: ',FMQTTState,' -> ',state);

**Comment by JacoFourie** [comment]
Haha OK so I found where my messages where comming from lol. It was messages set to retain so it got sent as soon as I connected. All seems to be fine now. Thanks soo much for your hard work.
