### ISSUE TITLE
ctypes - missing

### ISSUE THREAD

**Issue by jaclas** [chainq/mosquitto-p#6]
Pleas provide missing ctypes.pas unit.

**Comment by chainq** [comment]
Unit `ctypes` is part of Free Pascal. With what compiler or for platform are you trying to compile?

**Comment by jaclas** [comment]
I'm using Delphi, looking for an MQTT client library, didn't know FPC had this file. Sorry.

**Comment by chainq** [comment]
I'd be happy if someone added Delphi compatibility into this library. Most likely this can be done by adding a Delphi-specific `ctypes` unit (by adapting FPC's maybe?), and maybe a few syntax changes here or there. But I'm not going to do it myself, as Delphi is not my particular interest. Pull requests are welcomed though. Closing, as the original issue is solved.
