### ISSUE TITLE
Client ID ?

### ISSUE THREAD

**Issue by JacoFourie** [chainq/mosquitto-p#7]
Hi.

I do not see a client ID in the object method of connecting. How do I specify the client id ?

**Comment by chainq** [comment]
There isn't one. There is #3 and I asked the PR issuer to fix the code style of their PR, but they never have. I will integrate the changes now.

**Comment by chainq** [comment]
The requested functionality is now added in fae9760. It's now possible to specify a client ID, using the new `client_id` string field of the config passed to the class constructor. Please report any issues.

**Comment by JacoFourie** [comment]
Hi. Great thanks. I added it myself in a different way but used your code now to keep it standard.

All seems to be working fine at this point.
